### ISSUE TITLE
New QOLE needed

### ISSUE THREAD

**Issue by mitchellhumphrey** [NicholasMoser/qole-releases#2]
Training mode and costume fix for sakura and ino.

**Comment by NicholasMoser** [comment]
Also to be included

- Throw break inconsistency
- Game ID needs to change again, G5NJDA is seen by Nintendont it as Namco Museum: 50th Anniversary. But there's more: per GameTDB, that game's ID is G5NEAF.

**Comment by NicholasMoser** [comment]
https://github.com/NicholasMoser/qole-releases/releases/tag/1.4.0
